### ISSUE TITLE
tiktok-cookie-example.txt  How is this file configured?

### ISSUE THREAD

**Issue by bubaishaolong** [hienpro1302/tiktok-downloader#2]
tiktok-cookie-example.txt  How is this file configured?
Can you give an example?

**Comment by hienpro1302** [comment]
You should use the "You need using extension "Get cookies.txt LOCALLY"
extension to download cookies.
file example

Vào Th 2, 19 thg 2, 2024 vào lúc 15:24 鬼吹灯 ***@***.***> đã
viết:

**Comment by hienpro1302** [comment]
<img width="498" alt="Screenshot at Feb 19 15-34-38" src="https://github.com/hienpro1302/tiktok-downloader/assets/94742611/1a003102-3ed6-4648-a03a-86d2c705f683">
Example file
